# Generated by Django 4.2.11 on 2026-06-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('bio', models.TextField(verbose_name='bio')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d', verbose_name='image')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('instagram', models.CharField(max_length=100, verbose_name='instagram ')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='image')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=500, verbose_name='content')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('main_post', models.BooleanField(default=False, verbose_name='main_post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d', verbose_name='image')),
                ('video', models.FileField(upload_to='gallery/%Y/%m/%d', verbose_name='video')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.category')),
            ],
        ),
    ]
