# Generated by Django 4.2.11 on 2026-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='aparat_embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='aparat embed code'),
        ),
    ]
