# Generated by Django 4.2.11 on 2026-06-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_sitetheme_remove_category_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetheme',
            name='theme',
            field=models.CharField(choices=[('dark_luxury', '🌑 Dark Luxury — تاریک و طلایی'), ('midnight_blue', '🌊 Midnight Blue — آبی نفتی'), ('ivory_classic', '🌿 Ivory Classic — روشن و کلاسیک'), ('deep_emerald', '💎 Deep Emerald — زمردی تیره'), ('crimson_night', '🔴 Crimson Night — قرمز تیره')], default='dark_luxury', max_length=30, verbose_name='تم سایت'),
        ),
    ]
